In [18]:
import pandas as pd

In [19]:
df = pd.read_csv('customer.csv')

In [20]:
df.sample(5)

    age  gender   review education purchased
39   76    Male     Poor        PG        No
10   98  Female     Good        UG       Yes
29   83  Female  Average        UG       Yes
3    72  Female     Good        PG        No
0    30  Female  Average    School        No

In [21]:
df = df.iloc[:, 2:]

In [22]:
df.iloc[:, 0:2]

     review education
0   Average    School
1      Poor        UG
2      Good        PG
3      Good        PG
4   Average        UG
5   Average    School
6      Good    School
7      Poor    School
8   Average        UG
9      Good        UG
10     Good        UG
11     Good        UG
12     Poor    School
13  Average    School
14     Poor        PG
15     Poor        UG
16     Poor        UG
17     Poor        UG
18     Good    School
19     Poor        PG
20  Average    School
21  Average        PG
22     Poor        PG
23     Good    School
24  Average        PG
25     Good    School
26     Poor        PG
27     Poor        PG
28     Poor    School
29  Average        UG
30  Average        UG
31     Poor    School
32  Average        UG
33     Good        PG
34  Average    School
35     Poor    School
36     Good        UG
37  Average        PG
38     Good    School
39     Poor        PG
40     Good    School
41     Good        PG
42     Good        PG
43     Poor        PG
44  Average        UG
45     Poor        PG
46     Poor        PG
47     Good        PG
48     Good        UG
49     Good        UG

In [23]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test = train_test_split(df.iloc[:,0:2], df.iloc[:, -1], test_size=0.2)

In [25]:
from sklearn.preprocessing import OrdinalEncoder
oe = OrdinalEncoder(categories=[["Poor", "Average", "Good"], ["School", "UG","PG"]])

In [29]:
oe.fit(X_train)

X_train = oe.transform(X_train)
X_test = oe.transform(X_test)

In [30]:
X_train

array([[2., 1.],
       [2., 2.],
       [2., 0.],
       [2., 1.],
       [2., 0.],
       [2., 0.],
       [0., 1.],
       [1., 0.],
       [0., 0.],
       [2., 1.],
       [0., 1.],
       [1., 1.],
       [0., 2.],
       [0., 2.],
       [0., 1.],
       [2., 1.],
       [0., 2.],
       [2., 0.],
       [0., 1.],
       [0., 2.],
       [0., 0.],
       [1., 1.],
       [0., 2.],
       [1., 2.],
       [1., 0.],
       [1., 0.],
       [1., 1.],
       [2., 1.],
       [1., 1.],
       [1., 1.],
       [0., 0.],
       [2., 0.],
       [2., 0.],
       [1., 2.],
       [0., 2.],
       [1., 2.],
       [1., 0.],
       [1., 0.],
       [2., 2.],
       [0., 2.]])

In [32]:
oe.categories_

[array(['Poor', 'Average', 'Good'], dtype=object),
 array(['School', 'UG', 'PG'], dtype=object)]

In [31]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()

In [33]:
le.fit(y_train)

LabelEncoder()

In [34]:
le.classes_

array(['No', 'Yes'], dtype=object)

In [35]:
y_train = le.transform(y_train)
y_test = le.transform(y_test)

In [37]:
y_train

array([0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 1, 1, 0, 1, 1, 1, 0,
       0, 1, 0, 1, 0, 1, 0, 1, 1, 0, 0, 0, 1, 1, 0, 1, 1, 0])